IF EXISTS (SELECT 1 FROM SYS.DATABASES WHERE NAME = 'LUXURY_CARS')
BEGIN
    ALTER DATABASE LUXURY_CARS SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE LUXURY_CARS;
END

CREATE DATABASE LUXURY_CARS
GO

USE LUXURY_CARS
GO

CREATE TABLE TIPOCOMBUSTIBLES (
    IDCOMBUSTIBLE INT IDENTITY(1, 1) PRIMARY KEY,
    TIPOCOMBUSTIBLE VARCHAR(30) UNIQUE
)
GO

CREATE TABLE TIPOTRANSMISIONES (
    IDTRANSMISION INT IDENTITY(1, 1) PRIMARY KEY,
    TIPOTRANSMISION VARCHAR(30) UNIQUE
)
GO

CREATE TABLE TIPOFINANCIAMIENTOS (
    IDFINANCIAMIENTO INT IDENTITY(1, 1) PRIMARY KEY,
    TIPOFINANCIAMIENTO VARCHAR(30) UNIQUE
)
GO

CREATE TABLE MARCASCARROS (
    IDMARCA INT IDENTITY(1, 1) PRIMARY KEY,
    MARCA VARCHAR(30) UNIQUE
)
GO

CREATE TABLE MODELOSCARROS (
    IDMODELO INT IDENTITY(1, 1) PRIMARY KEY,
    IDMARCA INT,
    MODELO VARCHAR(50) UNIQUE,
    FOREIGN KEY (IDMARCA) REFERENCES MARCASCARROS(IDMARCA)
)
GO

CREATE TABLE CARROS (
    IDCARRO INT IDENTITY(1, 1) PRIMARY KEY,
    IDMODELO INT,
    ESTILO VARCHAR(50),
    ANIO INT,
    IDCOMBUSTIBLE INT,
    IDTRANSMISION INT,
    NUMEROPUERTAS INT,
    COLOREXTERIOR VARCHAR(50),
    COLORINTERIOR VARCHAR(50),
    FECHAINGRESO DATE,
    PLACA VARCHAR(25),
    IDFINANCIAMIENTO INT NULL,
    APARTADO VARCHAR(3) NULL,
    PRECIO DECIMAL(10, 2),
    FOREIGN KEY (IDMODELO) REFERENCES MODELOSCARROS(IDMODELO),
    FOREIGN KEY (IDCOMBUSTIBLE) REFERENCES TIPOCOMBUSTIBLES(IDCOMBUSTIBLE),
    FOREIGN KEY (IDTRANSMISION) REFERENCES TIPOTRANSMISIONES(IDTRANSMISION),
    FOREIGN KEY (IDFINANCIAMIENTO) REFERENCES TIPOFINANCIAMIENTOS(IDFINANCIAMIENTO)
)
GO

CREATE TABLE CARROSIMAGENES (
    IDIMAGEN INT IDENTITY(1, 1) PRIMARY KEY,
    IDCARRO INT,
    IMAGENPATH VARCHAR(255),
    FOREIGN KEY (IDCARRO) REFERENCES CARROS(IDCARRO)
)
GO

CREATE TABLE CATEGORIA (
    IDCATEGORIA INT IDENTITY(1, 1) PRIMARY KEY,
    TIPOCATEGORIA VARCHAR(30) UNIQUE
)
GO

CREATE TABLE PROVEEDORES (
    IDPROVEEDOR INT IDENTITY(1, 1) PRIMARY KEY,
    NOMBREPROVEEDOR VARCHAR(100),
    UBICACIONEMPRESA VARCHAR(300),
    CORREOELECTRONICOEMPRESA VARCHAR(50),
    NUMEROTELEFONICOEMPRESA VARCHAR(25)
)
GO

CREATE TABLE ESTADOS (
    IDESTADO INT IDENTITY(1, 1) PRIMARY KEY,
    NOMBREESTADO VARCHAR(30) UNIQUE
)
GO

CREATE TABLE PRODUCTOS (
    IDPRODUCTO INT IDENTITY(1, 1) PRIMARY KEY,
	IDCATEGORIA INT,
	IDPROVEEDOR INT,
    NOMBREPRODUCTO VARCHAR(30),
    PRECIO DECIMAL(10, 2),
    CANTIDADSTOCK INT,
    DESCRIPCION VARCHAR(300),
	ESTADO BIT,
	FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDORES(IDPROVEEDOR),
    FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA)
)
GO

CREATE TABLE IMAGENESPRODUCTOS (
    IDIMAGEN INT IDENTITY(1, 1) PRIMARY KEY,
    IDPRODUCTO INT,
    IMAGENPATH VARCHAR(255),
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(IDPRODUCTO)
)
GO

CREATE TABLE GENERO (
    IDGENERO INT IDENTITY(1, 1) PRIMARY KEY,
    TIPOGENERO VARCHAR(30)
)
GO

CREATE TABLE TIPOIDENTIFICACIONES (
    IDIDENTIFICACION INT IDENTITY(1, 1) PRIMARY KEY,
    TIPOIDENTIFICACION VARCHAR(30)
)
GO

CREATE TABLE ROLES (
    IDROL INT IDENTITY(1, 1) PRIMARY KEY,
    NOMBREROL VARCHAR(30) UNIQUE
)
GO

CREATE TABLE USUARIOS (
    IDUSUARIO INT IDENTITY(1, 1) PRIMARY KEY,
	IDTIPOIDENTIFICACION INT,
	IDROL INT,
    IDENTIFICACION VARCHAR(20) UNIQUE,
    NOMBRE VARCHAR(50),
    APELLIDO_MATERNO VARCHAR(50),
	APELLIDO_PATERNO VARCHAR(50),
	EMAIL VARCHAR(255) UNIQUE,
	CONTRASENNA VARCHAR(255),
    IDGENERO INT,
    TELEFONO VARCHAR(20) UNIQUE,
    DIRECCION VARCHAR(300),
	IMAGENPATH VARCHAR(255) NULL,
    FOREIGN KEY (IDGENERO) REFERENCES GENERO(IDGENERO),
    FOREIGN KEY (IDTIPOIDENTIFICACION) REFERENCES TIPOIDENTIFICACIONES(IDIDENTIFICACION),
    FOREIGN KEY (IDROL) REFERENCES ROLES(IDROL)
)
GO

CREATE TABLE METODOSDEPAGO (
    IDMETODOPAGO INT IDENTITY(1, 1) PRIMARY KEY,
    NOMBREMETODO VARCHAR(255) UNIQUE
)
GO

CREATE TABLE CARRITODECOMPRAS (
    IDCARRITO INT IDENTITY(1, 1) PRIMARY KEY,
    IDPRODUCTO INT,
    CANTIDADPRODUCTO INT,
    PRECIOUNITARIO DECIMAL(10, 2),
    IDESTADO INT,
    TOTAL DECIMAL(10, 2),
    FECHACREACION DATETIME,
    IDUSUARIO INT NULL,
	FOREIGN KEY (IDESTADO) REFERENCES ESTADOS(IDESTADO),
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(IDPRODUCTO),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO)
)
GO

CREATE TABLE FACTURACION (
    IDFACTURA INT IDENTITY(1, 1) PRIMARY KEY,
    IDUSUARIO INT,
    DESCRIPCION VARCHAR(300),
    FECHA DATE,
    IDESTADO INT,
    TOTALFACTURA DECIMAL(10, 2),
    DIRECCIONENVIO VARCHAR(300),
    IDMETODOPAGO INT,
    NUMEROFACTURA VARCHAR(20) UNIQUE,
	FOREIGN KEY (IDESTADO) REFERENCES ESTADOS(IDESTADO),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO),
    FOREIGN KEY (IDMETODOPAGO) REFERENCES METODOSDEPAGO(IDMETODOPAGO)
)
GO

CREATE TABLE HISTORIALCOMPRACARRO (
    IDHISTORIALCOMPRACARRO INT IDENTITY(1, 1) PRIMARY KEY,
    IDUSUARIO INT,
    IDCARRO INT,
    DESCRIPCION VARCHAR(300),
    FECHA DATETIME,
    IDESTADO INT,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO),
    FOREIGN KEY (IDCARRO) REFERENCES CARROS(IDCARRO),
    FOREIGN KEY (IDESTADO) REFERENCES ESTADOS(IDESTADO)
)
GO

INSERT INTO TIPOCOMBUSTIBLES (TIPOCOMBUSTIBLE) VALUES ('GASOLINA')
GO
INSERT INTO TIPOCOMBUSTIBLES (TIPOCOMBUSTIBLE) VALUES ('DIESEL')
GO
INSERT INTO TIPOCOMBUSTIBLES (TIPOCOMBUSTIBLE) VALUES ('GAS NATURAL')
GO

INSERT INTO TIPOTRANSMISIONES (TIPOTRANSMISION) VALUES ('AUTOMATICA')
GO
INSERT INTO TIPOTRANSMISIONES (TIPOTRANSMISION) VALUES ('MANUAL')
GO
INSERT INTO TIPOTRANSMISIONES (TIPOTRANSMISION) VALUES ('CVT')
GO


INSERT INTO TIPOFINANCIAMIENTOS (TIPOFINANCIAMIENTO) VALUES ('PRESTAMO PERSONAL')
GO
INSERT INTO TIPOFINANCIAMIENTOS (TIPOFINANCIAMIENTO) VALUES ('TARJETA DE CREDITO')
GO
INSERT INTO TIPOFINANCIAMIENTOS (TIPOFINANCIAMIENTO) VALUES ('HIPOTECA')
GO

INSERT INTO MARCASCARROS (MARCA) VALUES ('TOYOTA')
GO
INSERT INTO MARCASCARROS (MARCA) VALUES ('HONDA')
GO
INSERT INTO MARCASCARROS (MARCA) VALUES ('FORD')
GO
INSERT INTO MARCASCARROS (MARCA) VALUES ('CHEVROLET')
GO
INSERT INTO MARCASCARROS (MARCA) VALUES ('NISSAN')
GO
INSERT INTO MARCASCARROS (MARCA) VALUES ('VOLKSWAGEN')
GO
INSERT INTO MARCASCARROS (MARCA) VALUES ('BMW')
GO

INSERT INTO MODELOSCARROS (IDMARCA, MODELO) VALUES (1, 'COROLLA')
GO
INSERT INTO MODELOSCARROS (IDMARCA, MODELO) VALUES (1, 'CAMRY')
GO
INSERT INTO MODELOSCARROS (IDMARCA, MODELO) VALUES (2, 'CIVIC')
GO
INSERT INTO MODELOSCARROS (IDMARCA, MODELO) VALUES (2, 'ACCORD')
GO
INSERT INTO MODELOSCARROS (IDMARCA, MODELO) VALUES (3, 'MUSTANG')
GO
INSERT INTO MODELOSCARROS (IDMARCA, MODELO) VALUES (3, 'F-150')
GO
INSERT INTO MODELOSCARROS (IDMARCA, MODELO) VALUES (4, 'SILVERADO')
GO
INSERT INTO MODELOSCARROS (IDMARCA, MODELO) VALUES (4, 'CRUZE')
GO
INSERT INTO MODELOSCARROS (IDMARCA, MODELO) VALUES (5, 'ALTIMA')
GO
INSERT INTO MODELOSCARROS (IDMARCA, MODELO) VALUES (5, 'ROGUE')
GO
INSERT INTO MODELOSCARROS (IDMARCA, MODELO) VALUES (6, 'GOLF')
GO
INSERT INTO MODELOSCARROS (IDMARCA, MODELO) VALUES (6, 'JETTA')
GO
INSERT INTO MODELOSCARROS (IDMARCA, MODELO) VALUES (7, '3 SERIES')
GO
INSERT INTO MODELOSCARROS (IDMARCA, MODELO) VALUES (7, 'X5')
GO

INSERT INTO GENERO (TIPOGENERO) VALUES ('MASCULINO')
GO
INSERT INTO GENERO (TIPOGENERO) VALUES ('FEMENINO')
GO
INSERT INTO GENERO (TIPOGENERO) VALUES ('OTRO')
GO

INSERT INTO ROLES (NOMBREROL) VALUES ('ADMINISTRADOR')
GO
INSERT INTO ROLES (NOMBREROL) VALUES ('USUARIO')
GO
INSERT INTO ROLES (NOMBREROL) VALUES ('CLIENTE')
GO

INSERT INTO TIPOIDENTIFICACIONES(TIPOIDENTIFICACION) VALUES ('CÉDULA DE IDENTIDAD')
GO
INSERT INTO TIPOIDENTIFICACIONES (TIPOIDENTIFICACION) VALUES ('PASAPORTE')
GO
INSERT INTO TIPOIDENTIFICACIONES (TIPOIDENTIFICACION) VALUES ('CÉDULA JURÍDICA')
GO
INSERT INTO METODOSDEPAGO (NOMBREMETODO) VALUES ('TARJETA DE CRÉDITO')
GO
INSERT INTO METODOSDEPAGO (NOMBREMETODO) VALUES ('PAYPAL')
GO
INSERT INTO METODOSDEPAGO (NOMBREMETODO) VALUES ('TRANSFERENCIA BANCARIA')
GO

INSERT INTO CARROS (IDMODELO, ESTILO, ANIO, IDCOMBUSTIBLE, IDTRANSMISION, NUMEROPUERTAS, COLOREXTERIOR, COLORINTERIOR, FECHAINGRESO, PLACA, IDFINANCIAMIENTO, APARTADO, PRECIO)
VALUES
-- TOYOTA
(1, 'SEDAN', 2023, 1, 1, 4, 'ROJO', 'NEGRO', '2023-01-01', 'ABC123', 1, 'NO', 25000.00),
(2, 'SEDAN', 2023, 2, 2, 4, 'AZUL', 'GRIS', '2023-02-02', 'DEF456', 2, 'SI', 27000.00),
-- HONDA
(3, 'SEDAN', 2023, 1, 1, 4, 'BLANCO', 'NEGRO', '2023-03-03', 'GHI789', 3, 'NO', 23000.00),
(4, 'SEDAN', 2023, 2, 2, 4, 'NEGRO', 'GRIS', '2023-04-04', 'JKL012', 1, 'NO', 26000.00),
-- FORD
(5, 'DEPORTIVO', 2023, 1, 3, 2, 'AMARILLO', 'NEGRO', '2023-05-05', 'MNO345', 2, 'SI', 30000.00),
(6, 'CAMIONETA', 2023, 2, 1, 4, 'GRIS', 'GRIS', '2023-06-06', 'PQR678', 3, 'NO', 32000.00),
-- CHEVROLET
(7, 'DEPORTIVO', 2023, 1, 3, 2, 'ROJO', 'NEGRO', '2023-07-07', 'STU901', 1, 'NO', 28000.00),
(8, 'SEDAN', 2023, 2, 1, 4, 'AZUL', 'GRIS', '2023-08-08', 'VWX234', 2, 'SI', 31000.00),
-- NISSAN
(9, 'CAMIONETA', 2023, 1, 2, 4, 'BLANCO', 'GRIS', '2023-09-09', 'YZA567', 3, 'NO', 29000.00),
(10, 'SEDAN', 2023, 2, 1, 4, 'NEGRO', 'NEGRO', '2023-10-10', 'BCD890', 1, 'NO', 27000.00),
-- VOLKSWAGEN
(11, 'CAMIONETA', 2023, 1, 2, 4, 'GRIS', 'GRIS', '2023-11-11', 'EFG123', 2, 'SI', 33000.00),
(12, 'SEDAN', 2023, 2, 1, 4, 'AZUL', 'NEGRO', '2023-12-12', 'HIJ456', 3, 'NO', 30000.00),
-- BMW
(13, 'DEPORTIVO', 2023, 1, 3, 2, 'NEGRO', 'NEGRO', '2023-01-13', 'KLM789', 1, 'NO', 35000.00),
(14, 'SUV', 2023, 2, 1, 4, 'BLANCO', 'GRIS', '2023-02-14', 'NOP012', 2, 'SI', 38000.00)
GO

INSERT INTO CARROSIMAGENES (IDCARRO, IMAGENPATH)
VALUES
-- TOYOTA
(1, 'https://drive.google.com/uc?export=download&id=1wbpuaKLQv6RkxF9ZXJc8A2MHfDlt_bGA'),
(2, 'https://drive.google.com/uc?export=download&id=1wbpuaKLQv6RkxF9ZXJc8A2MHfDlt_bGA'),
-- HONDA
(3, 'https://drive.google.com/uc?export=download&id=1wbpuaKLQv6RkxF9ZXJc8A2MHfDlt_bGA'),
(4, 'https://drive.google.com/uc?export=download&id=1wbpuaKLQv6RkxF9ZXJc8A2MHfDlt_bGA'),
-- FORD
(5, 'https://drive.google.com/uc?export=download&id=1wbpuaKLQv6RkxF9ZXJc8A2MHfDlt_bGA'),
(6, 'https://drive.google.com/uc?export=download&id=1wbpuaKLQv6RkxF9ZXJc8A2MHfDlt_bGA'),
-- CHEVROLET
(7, 'https://drive.google.com/uc?export=download&id=1wbpuaKLQv6RkxF9ZXJc8A2MHfDlt_bGA'),
(8, 'https://drive.google.com/uc?export=download&id=1wbpuaKLQv6RkxF9ZXJc8A2MHfDlt_bGA'),
-- NISSAN
(9, 'https://drive.google.com/uc?export=download&id=1wbpuaKLQv6RkxF9ZXJc8A2MHfDlt_bGA'),
(10, 'https://drive.google.com/uc?export=download&id=1wbpuaKLQv6RkxF9ZXJc8A2MHfDlt_bGA'),
-- VOLKSWAGEN
(11, 'https://drive.google.com/uc?export=download&id=1wbpuaKLQv6RkxF9ZXJc8A2MHfDlt_bGA'),
(12, 'https://drive.google.com/uc?export=download&id=1wbpuaKLQv6RkxF9ZXJc8A2MHfDlt_bGA'),
-- BMW
(13, 'https://drive.google.com/uc?export=download&id=1wbpuaKLQv6RkxF9ZXJc8A2MHfDlt_bGA'),
(14, 'https://drive.google.com/uc?export=download&id=1wbpuaKLQv6RkxF9ZXJc8A2MHfDlt_bGA')
GO

INSERT INTO CATEGORIA (TIPOCATEGORIA) VALUES ('ACEITES Y LUBRICANTES')
GO
INSERT INTO CATEGORIA (TIPOCATEGORIA) VALUES ('ACCESORIOS INTERIORES')
GO
INSERT INTO CATEGORIA (TIPOCATEGORIA) VALUES ('ACCESORIOS EXTERIORES')
GO

INSERT INTO PROVEEDORES (NOMBREPROVEEDOR, UBICACIONEMPRESA, CORREOELECTRONICOEMPRESA, NUMEROTELEFONICOEMPRESA)
VALUES
('ACEITEPRO', 'CIUDAD PROVEEDORA', 'INFO@ACEITEPRO.COM', '123-456-7890'),
('ACCESORIOSINT', 'ACCESORIOS CITY', 'SALES@ACCESORIOSINT.COM', '987-654-3210'),
('ACCESORIOSEXT', 'EXTERNAL PARTS CORP', 'CONTACT@EXTERNALPARTS.COM', '456-789-0123')
GO

INSERT INTO PRODUCTOS (IDCATEGORIA, IDPROVEEDOR, NOMBREPRODUCTO, PRECIO, CANTIDADSTOCK, DESCRIPCION, ESTADO)
VALUES
(1, 1, 'ACEITE SINTÉTICO 5W-30', 29.99, 100, 'ACEITE SINTÉTICO PARA MOTORES DE AUTOMÓVILES', 1),
(2, 2, 'FUNDAS PARA ASIENTOS DE CUERO', 49.99, 50, 'FUNDAS ELEGANTES PARA ASIENTOS DE CUERO', 1),
(3, 3, 'PROTECTOR DE PARACHOQUES', 19.99, 75, 'PROTECTOR DE PARACHOQUES RESISTENTE PARA AUTOS', 1),
(1, 1, 'ACEITE MINERAL 10W-40', 19.99, 80, 'ACEITE MINERAL PARA MOTORES DE AUTOMÓVILES', 1),
(2, 2, 'ALFOMBRILLAS PERSONALIZADAS', 34.99, 40, 'ALFOMBRILLAS PERSONALIZADAS PARA AUTOMÓVILES', 1),
(3, 3, 'ESPEJOS RETROVISORES CROMADOS', 59.99, 30, 'ESPEJOS RETROVISORES CROMADOS PARA AUTOS', 1)
GO

INSERT INTO IMAGENESPRODUCTOS (IDPRODUCTO, IMAGENPATH)
VALUES
(1, 'https://drive.google.com/uc?export=download&id=1uA9nWE07zwZvo53bklQzATxRwjg0UpvY'),
(2, 'https://drive.google.com/uc?export=download&id=1uA9nWE07zwZvo53bklQzATxRwjg0UpvY'),
(3, 'https://drive.google.com/uc?export=download&id=1uA9nWE07zwZvo53bklQzATxRwjg0UpvY'),
(4, 'https://drive.google.com/uc?export=download&id=1uA9nWE07zwZvo53bklQzATxRwjg0UpvY'),
(5, 'https://drive.google.com/uc?export=download&id=1uA9nWE07zwZvo53bklQzATxRwjg0UpvY'),
(6, 'https://drive.google.com/uc?export=download&id=1uA9nWE07zwZvo53bklQzATxRwjg0UpvY')
GO

INSERT INTO ESTADOS (NOMBREESTADO) VALUES ('DISPONIBLE')
GO
INSERT INTO ESTADOS (NOMBREESTADO) VALUES ('EN PROCESO')
GO
INSERT INTO ESTADOS (NOMBREESTADO) VALUES ('VENDIDO')
GO
INSERT INTO ESTADOS (NOMBREESTADO) VALUES ('CANCELADO')
GO